### ISSUE TITLE
conform to OIDC spec

### ISSUE THREAD

**Issue by philloooo** [uc-cdis/fence#20]
# TODO

[Core Requirements](http://openid.net/specs/openid-connect-core-1_0.html)

Whichever library is used for implementation (https://github.com/OpenIDC/pyoidc ?) should hopefully knock out many of these points for "free". Tests should cover most points regardless.

## Authentication Endpoint

- [ ] **Signing ID Tokens with RSA SHA-256**
    - *Requirement:* OPs MUST support signing ID Tokens with the RSA SHA-256 algorithm (an alg value of RS256), unless the OP only supports returning ID Tokens from the Token Endpoint (as is the case for the Authorization Code Flow) and only allows Clients to register specifying none as the requested ID Token signing algorithm.
    - *TODO:* OP only supports returning ID tokens from the token endpoint `/oauth2/token`, and  does not allow clients to specify a different signing algorithm.
- [ ] **Prompt Parameter**
    - *Requirement:* OPs MUST support the prompt parameter, as defined in Section 3.1.2, including the specified user interface behaviors such as none and login.
- [ ] **Display Parameter**
    - OPs MUST support the display parameter, as defined in Section 3.1.2. (Note that the minimum level of support required for this parameter is simply that its use must not result in an error.)
- [x] **Preferred Locales**
    - *Requirement:* OPs MUST support requests for preferred languages and scripts for the user interface and for Claims via the `ui_locales` and `claims_locales` request parameters, as defined in Section 3.1.2. (Note that the minimum level of support required for these parameters is simply to have their use not result in errors.)
- [ ] **Authentication Time**
    - *Requirement:* OPs MUST support returning the time at which the End-User authenticated via the `auth_time` Claim, when requested, as defined in Section 2.
- [ ] **Maximum Authentication Age**
    - *Requirement:* OPs MUST support enforcing a maximum authentication age via the `max_age` parameter, as defined in Section 3.1.2.
- [ ] **Authentication Context Class Reference**
    - *Requirement:* OPs MUST support requests for specific Authentication Context Class Reference values via the `acr_values` parameter, as defined in Section 3.1.2. (Note that the minimum level of support required for this parameter is simply to have its use not result in an error.)

## Miscellaneous

Ideally, we also implement [discovery](http://openid.net/specs/openid-connect-discovery-1_0.html) and [dynamic client registration](http://openid.net/specs/openid-connect-registration-1_0.html), but these are outside the scope of the core requirements of the OIDC spec (so not vital for MVP).
