### ISSUE TITLE
PXD-388 ⁃ security checklist

### ISSUE THREAD

**Issue by philloooo** [uc-cdis/fence#67]
- [ ] all tokens are with correct expiration time and respected by APIs
- [ ] revoked tokens are indeed revoked
- [ ] client's tokens have correct restriction for scopes
- [ ] user's tokens have correct restriction for scopes

checkmark when unittests are done
